org: jsstrn
app: daily-dad-jokes
service: daily-dad-jokes
frameworkVersion: "2"
useDotenv: true

plugins:
  - serverless-prune-plugin
  - serverless-dotenv-plugin
  - serverless-webpack

provider:
  name: aws
  region: ap-southeast-1
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  setWebhook:
    handler: src/functions/index.setWebhook
    events:
      - http:
          path: set-webhook
          method: get

  getWebhook:
    handler: src/functions/index.getWebhook
    events:
      - http:
          path: get-webhook
          method: get

  handleBotRequests:
    handler: src/functions/index.handleBotRequests
    events:
      - http:
          path: handleBotRequests
          method: post

  broadcastToChannel:
    handler: src/functions/index.broadcastToChannel
    events:
      - schedule:
          name: ${self:app}-${opt:stage}-once-every-day
          description: "Scheduled for once every day at 2am GMT"
          rate: cron(0 2 * * ? *)
          enabled: true
      - schedule:
          name: ${self:app}-${opt:stage}-once-every-minute
          description: "Scheduled for once every minute"
          rate: rate(1 minute)
          enabled: false
