org: jsstrn
app: daily-dad-jokes
service: daily-dad-jokes
frameworkVersion: "2"
useDotenv: true

plugins:
  - serverless-prune-plugin
  - serverless-dotenv-plugin

provider:
  name: aws
  region: ap-southeast-1
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  channelBroadcast:
    handler: index.run
    events:
      - schedule:
          name: once-every-day
          description: "Scheduled for once every day at 2am GMT"
          rate: cron(0 2 * * ? *)
          enabled: true
